misskey {
  misskey.host = ${?MISSKEY_HOST}

  reader {
    // "global" | "home" | "social" | "local"
    timeline = "global"
    timeline = ${?MISSKEY_TARGET_TIMELINE} 

    // 監視対象とするnoteの最も低い可視性
    // "public" | "home"
    minVisibility = "public"
    minVisibility = ${?MISSKEY_TARGET_MIN_VISIBILITY}

    excludeLocalOnly = true
    excludeLocalOnly = ${?MISSKEY_EXCLUDE_LOCAL_ONLY}
  }
}
